In [27]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline

In [28]:
df = pd.read_csv("insurance__data.csv")
df.head()

   age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [33]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['age','affordibility']],df.bought_insurance,test_size=0.2, random_state=25)

In [34]:
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age'] / 100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age'] / 100

In [ ]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(2,), activation='sigmoid', kernel_initializer='ones', bias_initializer='zeros')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(X_train_scaled, y_train, epochs=5000)

Epoch 1/5000

C:\Users\youss\miniconda3-pbe\envs\tensorflow\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 785ms/step - accuracy: 0.5000 - loss: 0.7113
Epoch 2/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5000 - loss: 0.7110
Epoch 3/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.7106
Epoch 4/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.7102
Epoch 5/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5000 - loss: 0.7098
Epoch 6/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.5000 - loss: 0.7094
Epoch 7/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.5000 - loss: 0.7091
Epoch 8/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.5000 - loss: 0.7087
Epoch 9/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5000 - loss: 0.7083
Epoch 10/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.5000 - loss: 0.7079
Epoch 11/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.7076
Epoch 12/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5000 - loss: 0.7072
Epoch 13/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.7068
Epoch 14/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.5000 - loss: 0.7065
Epoch 15/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 0.7061
Epoch 16/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.5000 - loss: 0.7057
Epoch 17/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.7054
Epoch 18/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.7050
Epoch 19/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5000 - loss: 0.7046
Epoch 20/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5000 - loss: 0.7043
Epoch 21/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5000 - loss: 0.7039
Epoch 22/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.7035
Epoch 23/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.7032
Epoch 24/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.7028
Epoch 25/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7025
Epoch 26/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.7021
Epoch 27/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5000 - loss: 0.7017
Epoch 28/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.7014
Epoch 29/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.7010
Epoch 30/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.7007
Epoch 31/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.7003
Epoch 32/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.7000
Epoch 33/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.6996
Epoch 34/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.6993
Epoch 35/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5000 - loss: 0.6989
Epoch 36/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5000 - loss: 0.6986
Epoch 37/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5000 - loss: 0.6982
Epoch 38/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.5000 - loss: 0.6979
Epoch 39/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5000 - loss: 0.6975
Epoch 40/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6972
Epoch 41/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.6969
Epoch 42/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6965
Epoch 43/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6962
Epoch 44/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.6958
Epoch 45/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.6955
Epoch 46/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.6952
Epoch 47/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5000 - loss: 0.6948
Epoch 48/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.6945
Epoch 49/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.6942
Epoch 50/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.6938
Epoch 51/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5000 - loss: 0.6935
Epoch 52/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6932
Epoch 53/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.6928
Epoch 54/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6925
Epoch 55/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.6922
Epoch 56/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.6918
Epoch 57/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.6915
Epoch 58/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.6912
Epoch 59/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.5000 - loss: 0.6909
Epoch 60/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.6906
Epoch 61/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.6902
Epoch 62/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.6899
Epoch 63/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.6896
Epoch 64/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.6893
Epoch 65/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.6890
Epoch 66/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.6886
Epoch 67/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.6883
Epoch 68/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.6880
Epoch 69/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 0.5000 - loss: 0.6877
Epoch 70/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5000 - loss: 0.6874
Epoch 71/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.6871
Epoch 72/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6868
Epoch 73/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.6865
Epoch 74/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.6862
Epoch 75/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.6859
Epoch 76/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.6856
Epoch 77/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.6853
Epoch 78/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.6849
Epoch 79/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.6846
Epoch 80/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.6843
Epoch 81/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.6840
Epoch 82/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.6838
Epoch 83/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.6835
Epoch 84/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - accuracy: 0.5000 - loss: 0.6832
Epoch 85/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.6829
Epoch 86/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.6826
Epoch 87/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.6823
Epoch 88/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.6820
Epoch 89/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.6817
Epoch 90/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.6814
Epoch 91/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6811
Epoch 92/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.5000 - loss: 0.6808
Epoch 93/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.5000 - loss: 0.6805
Epoch 94/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.5000 - loss: 0.6803
Epoch 95/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.6800
Epoch 96/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.5000 - loss: 0.6797
Epoch 97/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.5000 - loss: 0.6794
Epoch 98/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.6791
Epoch 99/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.6788
Epoch 100/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.6786
Epoch 101/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.6783
Epoch 102/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.6780
Epoch 103/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.6777
Epoch 104/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.6775
Epoch 105/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.6772
Epoch 106/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.6769
Epoch 107/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.5000 - loss: 0.6766
Epoch 108/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6764
Epoch 109/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.6761
Epoch 110/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.6758
Epoch 111/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.6756
Epoch 112/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6753
Epoch 113/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.6750
Epoch 114/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.6748
Epoch 115/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.6745
Epoch 116/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.6742
Epoch 117/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.5000 - loss: 0.6740
Epoch 118/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.6737
Epoch 119/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 0.6735
Epoch 120/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6732
Epoch 121/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.6730
Epoch 122/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.6727
Epoch 123/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.6724
Epoch 124/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.6722
Epoch 125/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.6719
Epoch 126/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.6717
Epoch 127/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.5000 - loss: 0.6714
Epoch 128/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 0.6712
Epoch 129/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.6709
Epoch 130/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.6707
Epoch 131/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.6704
Epoch 132/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.6702
Epoch 133/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.6699
Epoch 134/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.6697
Epoch 135/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5000 - loss: 0.6695
Epoch 136/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5000 - loss: 0.6692
Epoch 137/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.6690
Epoch 138/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.6687
Epoch 139/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.6685
Epoch 140/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 0.6683
Epoch 141/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.6680
Epoch 142/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.6678
Epoch 143/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.6675
Epoch 144/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.6673
Epoch 145/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.6671
Epoch 146/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.6668
Epoch 147/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5000 - loss: 0.6666
Epoch 148/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.6664
Epoch 149/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.6661
Epoch 150/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.6659
Epoch 151/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.6657
Epoch 152/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.6655
Epoch 153/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step - accuracy: 0.5000 - loss: 0.6652
Epoch 154/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.6650
Epoch 155/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 0.6648
Epoch 156/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5000 - loss: 0.6646
Epoch 157/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5000 - loss: 0.6643
Epoch 158/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.6641
Epoch 159/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.6639
Epoch 160/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5000 - loss: 0.6637
Epoch 161/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.6635
Epoch 162/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 0.6632
Epoch 163/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.6630
Epoch 164/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 0.6628
Epoch 165/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - accuracy: 0.5000 - loss: 0.6626
Epoch 166/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.6624
Epoch 167/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.6622
Epoch 168/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.6620
Epoch 169/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5000 - loss: 0.6617
Epoch 170/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.6615
Epoch 171/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.6613
Epoch 172/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5000 - loss: 0.6611
Epoch 173/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 0.5455 - loss: 0.6609
Epoch 174/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5455 - loss: 0.6607
Epoch 175/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5455 - loss: 0.6605
Epoch 176/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5455 - loss: 0.6603
Epoch 177/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5455 - loss: 0.6601
Epoch 178/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5455 - loss: 0.6599
Epoch 179/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5455 - loss: 0.6597
Epoch 180/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5455 - loss: 0.6595
Epoch 181/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5455 - loss: 0.6593
Epoch 182/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5455 - loss: 0.6591
Epoch 183/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5455 - loss: 0.6589
Epoch 184/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5455 - loss: 0.6587
Epoch 185/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5455 - loss: 0.6585
Epoch 186/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.5455 - loss: 0.6583
Epoch 187/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5455 - loss: 0.6581
Epoch 188/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5455 - loss: 0.6579
Epoch 189/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5455 - loss: 0.6577
Epoch 190/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5455 - loss: 0.6575
Epoch 191/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5455 - loss: 0.6573
Epoch 192/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5455 - loss: 0.6571
Epoch 193/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5455 - loss: 0.6569
Epoch 194/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5455 - loss: 0.6568
Epoch 195/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5455 - loss: 0.6566
Epoch 196/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5455 - loss: 0.6564
Epoch 197/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5455 - loss: 0.6562
Epoch 198/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5455 - loss: 0.6560
Epoch 199/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.5455 - loss: 0.6558
Epoch 200/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5455 - loss: 0.6556
Epoch 201/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5455 - loss: 0.6555
Epoch 202/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5455 - loss: 0.6553
Epoch 203/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5455 - loss: 0.6551
Epoch 204/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5455 - loss: 0.6549
Epoch 205/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5455 - loss: 0.6547
Epoch 206/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5455 - loss: 0.6545
Epoch 207/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5455 - loss: 0.6544
Epoch 208/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5455 - loss: 0.6542
Epoch 209/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5455 - loss: 0.6540
Epoch 210/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5455 - loss: 0.6538
Epoch 211/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5455 - loss: 0.6537
Epoch 212/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.5455 - loss: 0.6535
Epoch 213/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5455 - loss: 0.6533
Epoch 214/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5455 - loss: 0.6531
Epoch 215/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5455 - loss: 0.6530
Epoch 216/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5455 - loss: 0.6528
Epoch 217/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5455 - loss: 0.6526
Epoch 218/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5455 - loss: 0.6525
Epoch 219/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5455 - loss: 0.6523
Epoch 220/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5455 - loss: 0.6521
Epoch 221/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5455 - loss: 0.6519
Epoch 222/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5455 - loss: 0.6518
Epoch 223/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5455 - loss: 0.6516
Epoch 224/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5455 - loss: 0.6515
Epoch 225/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5455 - loss: 0.6513
Epoch 226/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5455 - loss: 0.6511
Epoch 227/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5455 - loss: 0.6510
Epoch 228/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5455 - loss: 0.6508
Epoch 229/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5455 - loss: 0.6506
Epoch 230/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5455 - loss: 0.6505
Epoch 231/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5455 - loss: 0.6503
Epoch 232/5000

In [36]:
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step

array([[0.70548475],
       [0.3556957 ],
       [0.16827832],
       [0.4780119 ],
       [0.72606957],
       [0.82949823]], dtype=float32)

In [38]:
y_test

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

In [39]:
coef, intercept = model.get_weights()
coef, intercept

(array([[5.0608625],
        [1.408652 ]], dtype=float32),
 array([-2.9137027], dtype=float32))

In [56]:
import numpy as np

def sigmoid_numpy(x):
    return 1 / (1 + np.exp(-x))

In [57]:
X_test

    age  affordibility
2    47              1
10   18              1
21   26              0
11   28              1
14   49              1
9    61              1

In [58]:
def prediction_function(age, affordibility):
    weighted_sum = coef[0]*age + coef[1]*affordibility + intercept
    return sigmoid(weighted_sum)

prediction_function(0.47, 1)

array([0.7054848], dtype=float32)

In [59]:
prediction_function(.18, 1)

array([0.3556957], dtype=float32)

In [60]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [61]:
def gradient_descent(age, affordability, y_true, epochs, loss_thresold):
    w1 = w2 = 1
    bias = 0
    rate = 0.5
    n = len(age)
    for i in range(epochs):
        weighted_sum = w1 * age + w2 * affordability + bias
        y_predicted = sigmoid_numpy(weighted_sum)
        loss = log_loss(y_true, y_predicted)

        w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true)) 
        w2d = (1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true)) 

        bias_d = np.mean(y_predicted-y_true)
        w1 = w1 - rate * w1d
        w2 = w2 - rate * w2d
        bias = bias - rate * bias_d

        print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')

        if loss<=loss_thresold:
            break

    return w1, w2, bias

In [62]:
gradient_descent(X_train_scaled['age'],X_train_scaled['affordibility'],y_train,1000, 0.4631)

Epoch:0, w1:0.974907633470177, w2:0.948348125394529, bias:-0.11341867736368583, loss:0.7113403233723417
Epoch:1, w1:0.9556229728273669, w2:0.9058873696677865, bias:-0.2122349122718517, loss:0.681264778737757
Epoch:2, w1:0.9416488476693794, w2:0.8719790823960313, bias:-0.2977578997796538, loss:0.6591474252715025
Epoch:3, w1:0.9323916996249162, w2:0.8457541517722915, bias:-0.3715094724003511, loss:0.6431523291301917
Epoch:4, w1:0.9272267472726993, w2:0.8262362885332687, bias:-0.43506643026891584, loss:0.6316873063379158
Epoch:5, w1:0.9255469396815343, w2:0.8124402814952774, bias:-0.48994490058938817, loss:0.623471707997592
Epoch:6, w1:0.9267936114129968, w2:0.8034375029757677, bias:-0.5375299543522853, loss:0.6175321183044205
Epoch:7, w1:0.93047170420295, w2:0.7983920007454487, bias:-0.5790424270894963, loss:0.6131591858705934
Epoch:8, w1:0.9361540784567942, w2:0.7965748796787705, bias:-0.6155315088627655, loss:0.6098518179750948
Epoch:9, w1:0.9434791243557357, w2:0.7973647616854131, bias:-0.6478828179413606, loss:0.6072639970231438
Epoch:10, w1:0.9521448361628082, w2:0.8002404280558159, bias:-0.6768343869109611, loss:0.6051606942838051
Epoch:11, w1:0.9619014360798376, w2:0.8047697991276092, bias:-0.7029956527236098, loss:0.6033841405177724
Epoch:12, w1:0.9725437902239876, w2:0.8105978078160995, bias:-0.7268665798879941, loss:0.6018292976282692
Epoch:13, w1:0.9839042828641819, w2:0.8174345999952901, bias:-0.7488554155033402, loss:0.6004266142491015
Epoch:14, w1:0.9958464546516588, w2:0.8250447751055391, bias:-0.769294418817745, loss:0.5991301804031037
Epoch:15, w1:1.0082595007242081, w2:0.8332379503132499, bias:-0.7884533918133878, loss:0.5979097221992564
Epoch:16, w1:1.0210536111133566, w2:0.8418606908070436, bias:-0.8065510935633605, loss:0.5967452540340851
Epoch:17, w1:1.034156080666481, w2:0.8507897246509063, bias:-0.8237647415878959, loss:0.5956235357679642
Epoch:18, w1:1.0475080939682688, w2:0.8599263049589658, bias:-0.8402378469114854, loss:0.5945357398126384
Epoch:19, w1:1.0610620872868053, w2:0.8691915649552581, bias:-0.8560866317233403, loss:0.5934759216594547
Epoch:20, w1:1.0747795953648005, w2:0.8785227146485403, bias:-0.8714052604012273, loss:0.5924400203169505
Epoch:21, w1:1.0886295007650375, w2:0.8878699408379153, bias:-0.8862700880092956, loss:0.5914252065214394
Epoch:22, w1:1.1025866146156011, w2:0.8971938890119441, bias:-0.9007431016492755, loss:0.5904294583596238
Epoch:23, w1:1.1166305284975315, w2:0.9064636231844676, bias:-0.9148747025148294, loss:0.5894512852039241
Epoch:24, w1:1.130744687166233, w2:0.9156549761872753, bias:-0.9287059516737735, loss:0.5884895481881011
Epoch:25, w1:1.1449156405234902, w2:0.9247492176815199, bias:-0.9422703810055986, loss:0.5875433434377384
Epoch:26, w1:1.1591324407175467, w2:0.9337319799254573, bias:-0.9555954523596437, loss:0.5866119260562087
Epoch:27, w1:1.1733861565198167, w2:0.9425923921787205, bias:-0.9687037326284236, loss:0.5856946605640079
Epoch:28, w1:1.1876694823356402, w2:0.9513223836938425, bias:-0.9816138397030203, loss:0.5847909885040025
Epoch:29, w1:1.2019764234961199, w2:0.9599161227563919, bias:-0.994341203820797, loss:0.5839004071862915
Epoch:30, w1:1.2163020429886013, w2:0.9683695654077998, bias:-1.006898680274023, loss:0.5830224556644095
Epoch:31, w1:1.2306422576428844, w2:0.9766800925300213, bias:-1.0192970425003876, loss:0.5821567054089575
Epoch:32, w1:1.244993674111329, w2:0.9848462180774323, bias:-1.0315453789434794, loss:0.5813027540359855
Epoch:33, w1:1.2593534568600255, w2:0.9928673545729692, bias:-1.0436514125153917, loss:0.5804602210251408
Epoch:34, w1:1.2737192219062514, w2:1.0007436246821175, bias:-1.0556217578155669, loss:0.5796287447370064
Epoch:35, w1:1.2880889512619975, w2:1.0084757098569885, bias:-1.067462128294764, loss:0.57880798028165
Epoch:36, w1:1.3024609240300042, w2:1.0160647288004139, bias:-1.079177503164993, loss:0.5779975979476322
Epoch:37, w1:1.3168336608930384, w2:1.0235121399165894, bias:-1.0907722619345364, loss:0.5771972820026156
Epoch:38, w1:1.3312058793761508, w2:1.0308196630555955, bias:-1.1022502929016078, loss:0.5764067297427645
Epoch:39, w1:1.3455764577755067, w2:1.03798921677727, bias:-1.1136150806976406, loss:0.5756256507109632
Epoch:40, w1:1.3599444060604624, w2:1.0450228680985851, bias:-1.124869776972519, loss:0.5748537660316542
Epoch:41, w1:1.3743088423875545, w2:1.0519227922827652, bias:-1.1360172575115421, loss:0.5740908078281305
Epoch:42, w1:1.3886689741318716, w2:1.0586912407061275, bias:-1.1470601684290498, loss:0.5733365186998219
Epoch:43, w1:1.4030240825556768, w2:1.065330515222758, bias:-1.1580009635655026, loss:0.5725906512447178
Epoch:44, w1:1.4173735104064382, w2:1.0718429477560005, bias:-1.1688419347984433, loss:0.5718529676170188
Epoch:45, w1:1.4317166518748927, w2:1.0782308840940895, bias:-1.1795852366431911, loss:0.5711232391133308
Epoch:46, w1:1.4460529444550507, w2:1.0844966710669584, bias:-1.1902329062502135, loss:0.5704012457828124
Epoch:47, w1:1.4603818623375084, w2:1.0906426464418717, bias:-1.2007868796899672, loss:0.5696867760580651
Epoch:48, w1:1.474702911039356, w2:1.0966711310047097, bias:-1.2112490052422353, loss:0.5689796264044564
Epoch:49, w1:1.4890156230318012, w2:1.1025844223976542, bias:-1.2216210542672539, loss:0.5682796009861607
Epoch:50, w1:1.503319554173139, w2:1.108384790367645, bias:-1.2319047301235464, loss:0.5675865113475955
Epoch:51, w1:1.5176142807921111, w2:1.1140744731472638, bias:-1.2421016755069894, loss:0.5669001761092021
Epoch:52, w1:1.5318993972968091, w2:1.1196556747438646, bias:-1.2522134785128962, loss:0.566220420676692
Epoch:53, w1:1.546174514208496, w2:1.1251305629563741, bias:-1.2622416776643735, loss:0.5655470769630154
Epoch:54, w1:1.5604392565392238, w2:1.1305012679742994, bias:-1.2721877661030871, loss:0.5648799831223866
Epoch:55, w1:1.5746932624478314, w2:1.1357698814417572, bias:-1.2820531951006382, loss:0.5642189832957764
Epoch:56, w1:1.5889361821215457, w2:1.1409384558921223, bias:-1.2918393770181935, loss:0.5635639273673236
Epoch:57, w1:1.6031676768405996, w2:1.1460090044772484, bias:-1.3015476878174077, loss:0.562914670731162
Epoch:58, w1:1.6173874181914885, w2:1.150983500930006, bias:-1.3111794692058374, loss:0.5622710740681858
Epoch:59, w1:1.6315950874010996, w2:1.155863879710811, bias:-1.320736030484068, loss:0.5616330031323111
Epoch:60, w1:1.6457903747692835, w2:1.1606520362984267, bias:-1.3302186501488862, loss:0.5610003285458062
Epoch:61, w1:1.6599729791817353, w2:1.1653498275930778, bias:-1.3396285772964385, loss:0.5603729256032908
Epoch:62, w1:1.6741426076885264, w2:1.1699590724061661, bias:-1.348967032860937, loss:0.5597506740840237
Epoch:63, w1:1.6882989751364197, w2:1.1744815520159209, bias:-1.3582352107177078, loss:0.5591334580721091
Epoch:64, w1:1.7024418038453646, w2:1.1789190107723873, bias:-1.3674342786739169, loss:0.5585211657842806
Epoch:65, w1:1.7165708233213919, w2:1.1832731567384374, bias:-1.3765653793659074, loss:0.5579136894049259
Epoch:66, w1:1.7306857699995972, w2:1.1875456623561378, bias:-1.385629631078514, loss:0.5573109249280388
Epoch:67, w1:1.744786387012096, w2:1.1917381651299463, bias:-1.3946281284988502, loss:0.556712772005794
Epoch:68, w1:1.7588724239767908, w2:1.1958522683199346, bias:-1.4035619434147377, loss:0.5561191338034575
Epoch:69, w1:1.7729436368035707, w2:1.199889541639625, bias:-1.412432125366066, loss:0.5555299168603557
Epoch:70, w1:1.786999787515191, w2:1.2038515219541523, bias:-1.4212397022558536, loss:0.55494503095664
Epoch:71, w1:1.8010406440805895, w2:1.2077397139753707, bias:-1.4299856809265468, loss:0.5543643889855958
Epoch:72, w1:1.815065980258806, w2:1.21155559095125, bias:-1.4386710477060998, loss:0.5537879068312537
Epoch:73, w1:1.8290755754520085, w2:1.2153005953475013, bias:-1.4472967689275704, loss:0.5532155032510755
Epoch:74, w1:1.8430692145663952, w2:1.2189761395198406, bias:-1.4558637914253105, loss:0.5526470997634942
Epoch:75, w1:1.857046687879965, w2:1.2225836063756854, bias:-1.4643730430103006, loss:0.5520826205400979
Epoch:76, w1:1.8710077909163219, w2:1.2261243500243837, bias:-1.472825432926746, loss:0.5515219923022593
Epoch:77, w1:1.8849523243238275, w2:1.2295996964153224, bias:-1.4812218522917016, loss:0.5509651442220168
Epoch:78, w1:1.898880093759531, w2:1.2330109439634602, bias:-1.4895631745192046, loss:0.5504120078270269
Epoch:79, w1:1.9127909097773987, w2:1.2363593641619885, bias:-1.4978502557301687, loss:0.5498625169094129
Epoch:80, w1:1.9266845877204517, w2:1.2396462021819508, bias:-1.5060839351490927, loss:0.5493166074383391
Epoch:81, w1:1.9405609476164691, w2:1.2428726774587495, bias:-1.5142650354884937, loss:0.5487742174761587
Epoch:82, w1:1.9544198140769822, w2:1.2460399842655545, bias:-1.5223943633218389, loss:0.5482352870979753
Epoch:83, w1:1.968261016199314, w2:1.2491492922736824, bias:-1.5304727094456483, loss:0.5476997583144769
Epoch:84, w1:1.9820843874714607, w2:1.252201747100074, bias:-1.538500849231359, loss:0.5471675749979029
Epoch:85, w1:1.995889765679638, w2:1.2551984708420285, bias:-1.5464795429674643, loss:0.5466386828110088
Epoch:86, w1:2.0096769928183367, w2:1.2581405625993878, bias:-1.554409536192387, loss:0.5461130291389041
Epoch:87, w1:2.023445915002755, w2:1.2610290989843815, bias:-1.5622915600184968, loss:0.545590563023641
Epoch:88, w1:2.037196382383489, w2:1.2638651346193672, bias:-1.5701263314476384, loss:0.5450712351014357
Epoch:89, w1:2.0509282490633733, w2:1.2666497026227028, bias:-1.577914553678509, loss:0.5445549975424178
Epoch:90, w1:2.0646413730163813, w2:1.2693838150830055, bias:-1.585656916406187, loss:0.5440418039927909
Epoch:91, w1:2.0783356160084976, w2:1.2720684635220503, bias:-1.5933540961140944, loss:0.5435316095193146
Epoch:92, w1:2.092010843520487, w2:1.2747046193465692, bias:-1.6010067563586592, loss:0.5430243705560023
Epoch:93, w1:2.1056669246724873, w2:1.2772932342892063, bias:-1.6086155480469115, loss:0.5425200448529465
Epoch:94, w1:2.1193037321503643, w2:1.2798352408388918, bias:-1.6161811097072503, loss:0.5420185914271816
Epoch:95, w1:2.1329211421337653, w2:1.282331552660889, bias:-1.62370406775359, loss:0.5415199705154982
Epoch:96, w1:2.1465190342258187, w2:1.2847830650067702, bias:-1.6311850367430925, loss:0.5410241435291299
Epoch:97, w1:2.1600972913844236, w2:1.2871906551145709, bias:-1.638624619627673, loss:0.5405310730102341
Epoch:98, w1:2.173655799855084, w2:1.2895551825993699, bias:-1.6460234079994696, loss:0.5400407225900913
Epoch:99, w1:2.1871944491052364, w2:1.2918774898345378, bias:-1.6533819823304428, loss:0.5395530569489538
Epoch:100, w1:2.200713131760032, w2:1.2941584023238903, bias:-1.6607009122062801, loss:0.5390680417774752
Epoch:101, w1:2.2142117435395288, w2:1.2963987290649803, bias:-1.667980756554761, loss:0.5385856437396539
Epoch:102, w1:2.227690183197251, w2:1.298599262903754, bias:-1.675222063868738, loss:0.5381058304372313
Epoch:103, w1:2.241148352460086, w2:1.300760780880796, bias:-1.6824253724238831, loss:0.5376285703754836
Epoch:104, w1:2.2545861559694704, w2:1.302884044569378, bias:-1.68959121049134, loss:0.5371538329303491
Epoch:105, w1:2.268003501223843, w2:1.3049698004055226, bias:-1.696720096545423, loss:0.5366815883168389
Epoch:106, w1:2.281400298522321, w2:1.30701878001029, bias:-1.7038125394664934, loss:0.5362118075586769
Epoch:107, w1:2.294776460909571, w2:1.3090317005044871, bias:-1.7108690387391425, loss:0.5357444624591193
Epoch:108, w1:2.308131904121845, w2:1.3110092648159952, bias:-1.717890084645807, loss:0.5352795255729065
Epoch:109, w1:2.3214665465341486, w2:1.3129521619799067, bias:-1.7248761584559342, loss:0.5348169701793002
Epoch:110, w1:2.334780309108516, w2:1.3148610674316565, bias:-1.7318277326108187, loss:0.5343567702561651
Epoch:111, w1:2.3480731153433556, w2:1.3167366432933292, bias:-1.7387452709042173, loss:0.5338989004550466
Epoch:112, w1:2.361344891223853, w2:1.318579538653317, bias:-1.7456292286588566, loss:0.5334433360772121
Epoch:113, w1:2.3745955651733888, w2:1.3203903898394993, bias:-1.752480052898938, loss:0.5329900530506113
Epoch:114, w1:2.387825068005961, w2:1.3221698206861112, bias:-1.759298182518741, loss:0.532539027907722
Epoch:115, w1:2.4010333328795768, w2:1.3239184427944621, bias:-1.7660840484474298, loss:0.5320902377642434
Epoch:116, w1:2.4142202952505927, w2:1.3256368557876617, bias:-1.772838073810153, loss:0.5316436602986057
Epoch:117, w1:2.427385892828985, w2:1.3273256475595065, bias:-1.7795606740855376, loss:0.5311992737322607
Epoch:118, w1:2.440530065534521, w2:1.328985394517677, bias:-1.7862522572596642, loss:0.5307570568107249
Epoch:119, w1:2.4536527554538115, w2:1.3306166618213877, bias:-1.7929132239766132, loss:0.5303169887853427
Epoch:120, w1:2.46675390679823, w2:1.332220003613633, bias:-1.7995439676856702, loss:0.5298790493957434
Epoch:121, w1:2.479833465862666, w2:1.3337959632481655, bias:-1.8061448747852695, loss:0.5294432188529623
Epoch:122, w1:2.4928913809851023, w2:1.3353450735113397, bias:-1.8127163247637639, loss:0.5290094778232023
Epoch:123, w1:2.505927602506996, w2:1.336867856838949, bias:-1.8192586903370926, loss:0.5285778074122077
Epoch:124, w1:2.518942082734439, w2:1.3383648255281848, bias:-1.82577233758343, loss:0.5281481891502279
Epoch:125, w1:2.5319347759000843, w2:1.3398364819448387, bias:-1.832257626074885, loss:0.5277206049775486
Epoch:126, w1:2.5449056381258233, w2:1.341283318725866, bias:-1.8387149090063277, loss:0.5272950372305655
Epoch:127, w1:2.557854627386187, w2:1.3427058189774277, bias:-1.8451445333214114, loss:0.5268714686283816
Epoch:128, w1:2.570781703472466, w2:1.3441044564685243, bias:-1.851546839835858, loss:0.5264498822599072
Epoch:129, w1:2.583686827957526, w2:1.345479695820328, bias:-1.857922163358077, loss:0.5260302615714416
Epoch:130, w1:2.596569964161304, w2:1.346831992691322, bias:-1.8642708328071762, loss:0.5256125903547197
Epoch:131, w1:2.6094310771169726, w2:1.3481617939583521, bias:-1.8705931713284367, loss:0.5251968527354035
Epoch:132, w1:2.6222701335377554, w2:1.3494695378936876, bias:-1.8768894964063034, loss:0.524783033162003
Epoch:133, w1:2.635087101784378, w2:1.3507556543381913, bias:-1.8831601199749577, loss:0.5243711163952075
Epoch:134, w1:2.647881951833145, w2:1.3520205648706964, bias:-1.8894053485265268, loss:0.5239610874976152
Epoch:135, w1:2.660654655244622, w2:1.353264682973678, bias:-1.8956254832169885, loss:0.5235529318238407
Epoch:136, w1:2.6734051851329177, w2:1.3544884141953148, bias:-1.901820819969824, loss:0.5231466350109902
Epoch:137, w1:2.686133516135547, w2:1.3556921563080242, bias:-1.9079916495774736, loss:0.5227421829694884
Epoch:138, w1:2.6988396243838655, w2:1.3568762994635601, bias:-1.9141382578006458, loss:0.5223395618742417
Epoch:139, w1:2.7115234874740595, w2:1.3580412263447545, bias:-1.920260925465534, loss:0.5219387581561296
Epoch:140, w1:2.724185084438686, w2:1.3591873123139828, bias:-1.9263599285589843, loss:0.521539758493806
Epoch:141, w1:2.736824395718745, w2:1.3603149255584348, bias:-1.9324355383216678, loss:0.5211425498058037
Epoch:142, w1:2.7494414031362733, w2:1.3614244272322646, bias:-1.9384880213393003, loss:0.5207471192429267
Epoch:143, w1:2.7620360898674554, w2:1.3625161715956964, bias:-1.9445176396319575, loss:0.5203534541809204
Epoch:144, w1:2.7746084404162294, w2:1.363590506151157, bias:-1.9505246507415273, loss:0.5199615422134104
Epoch:145, w1:2.787158440588389, w2:1.364647771776508, bias:-1.9565093078173448, loss:0.5195713711450981
Epoch:146, w1:2.7996860774661636, w2:1.3656883028554423, bias:-1.9624718597000501, loss:0.5191829289852049
Epoch:147, w1:2.812191339383268, w2:1.3667124274051172, bias:-1.9684125510037105, loss:0.5187962039411522
Epoch:148, w1:2.824674215900416, w2:1.3677204672010856, bias:-1.974331622196247, loss:0.5184111844124737
Epoch:149, w1:2.8371346977812824, w2:1.3687127378995887, bias:-1.9802293096782038, loss:0.5180278589849453
Epoch:150, w1:2.8495727769689085, w2:1.3696895491572745, bias:-1.986105845859897, loss:0.5176462164249294
Epoch:151, w1:2.861988446562542, w2:1.3706512047484, bias:-1.9919614592369834, loss:0.5172662456739209
Epoch:152, w1:2.8743817007948973, w2:1.3715980026795769, bias:-1.9977963744644796, loss:0.5168879358432925
Epoch:153, w1:2.886752535009837, w2:1.3725302353021163, bias:-2.003610812429271, loss:0.5165112762092271
Epoch:154, w1:2.899100945640455, w2:1.373448189422031, bias:-2.009404990321143, loss:0.5161362562078318
Epoch:155, w1:2.9114269301875644, w2:1.3743521464077455, bias:-2.015179121702366, loss:0.515762865430428
Epoch:156, w1:2.9237304871985708, w2:1.3752423822955708, bias:-2.0209334165758692, loss:0.5153910936190104
Epoch:157, w1:2.9360116162467342, w2:1.376119167892991, bias:-2.0266680814520357, loss:0.515020930661866
Epoch:158, w1:2.9482703179108047, w2:1.3769827688798149, bias:-2.032383319414142, loss:0.5146523665893518
Epoch:159, w1:2.960506593755025, w2:1.3778334459072408, bias:-2.038079330182483, loss:0.514285391569821
Epoch:160, w1:2.9727204463094963, w2:1.3786714546948804, bias:-2.0437563101772027, loss:0.5139199959056945
Epoch:161, w1:2.984911879050898, w2:1.3794970461257903, bias:-2.0494144525798648, loss:0.5135561700296716
Epoch:162, w1:2.9970808963835545, w2:1.3803104663395542, bias:-2.0550539473937857, loss:0.5131939045010747
Epoch:163, w1:3.0092275036208402, w2:1.3811119568234618, bias:-2.0606749815031633, loss:0.5128331900023233
Epoch:164, w1:3.0213517069669225, w2:1.3819017545018246, bias:-2.0662777387310216, loss:0.5124740173355311
Epoch:165, w1:3.0334535134988276, w2:1.382680091823474, bias:-2.0718623998960024, loss:0.5121163774192251
Epoch:166, w1:3.045532931148832, w2:1.3834471968474789, bias:-2.0774291428680245, loss:0.5117602612851783
Epoch:167, w1:3.0575899686871653, w2:1.384203293327124, bias:-2.08297814262284, loss:0.511405660075352
Epoch:168, w1:3.069624635705023, w2:1.384948600792189, bias:-2.0885095712955057, loss:0.5110525650389491
Epoch:169, w1:3.081636942597884, w2:1.385683334629563, bias:-2.094023598232799, loss:0.5107009675295656
Epoch:170, w1:3.093626900549122, w2:1.386407706162234, bias:-2.0995203900445953, loss:0.5103508590024443
Epoch:171, w1:3.105594521513913, w2:1.387121922726688, bias:-2.1050001106542355, loss:0.5100022310118232
Epoch:172, w1:3.117539818203424, w2:1.387826187748753, bias:-2.110462921347898, loss:0.5096550752083747
Epoch:173, w1:3.1294628040692873, w2:1.3885207008179221, bias:-2.1159089808230034, loss:0.5093093833367357
Epoch:174, w1:3.141363493288346, w2:1.3892056577601883, bias:-2.121338445235668, loss:0.5089651472331199
Epoch:175, w1:3.1532419007476733, w2:1.389881250709425, bias:-2.1267514682472277, loss:0.5086223588230153
Epoch:176, w1:3.165098042029856, w2:1.390547668177342, bias:-2.132148201069852, loss:0.5082810101189588
Epoch:177, w1:3.176931933398537, w2:1.3912050951220503, bias:-2.1375287925112674, loss:0.5079410932183875
Epoch:178, w1:3.188743591784215, w2:1.3918537130152622, bias:-2.1428933890186115, loss:0.5076026003015645
Epoch:179, w1:3.200533034770296, w2:1.3924936999081612, bias:-2.1482421347214276, loss:0.5072655236295737
Epoch:180, w1:3.212300280579388, w2:1.3931252304959654, bias:-2.1535751714738307, loss:0.5069298555423847
Epoch:181, w1:3.2240453480598403, w2:1.3937484761812156, bias:-2.158892638895851, loss:0.5065955884569808
Epoch:182, w1:3.235768256672519, w2:1.3943636051358148, bias:-2.1641946744139777, loss:0.5062627148655543
Epoch:183, w1:3.2474690264778157, w2:1.394970782361845, bias:-2.1694814133009186, loss:0.505931227333758
Epoch:184, w1:3.2591476781228836, w2:1.3955701697511878, bias:-2.1747529887145927, loss:0.5056011184990193
Epoch:185, w1:3.270804232829102, w2:1.3961619261439753, bias:-2.1800095317363692, loss:0.505272381068909
Epoch:186, w1:3.2824387123797556, w2:1.3967462073858943, bias:-2.185251171408572, loss:0.5049450078195657
Epoch:187, w1:3.294051139107937, w2:1.3973231663843697, bias:-2.1904780347712607, loss:0.5046189915941715
Epoch:188, w1:3.3056415358846545, w2:1.3978929531636493, bias:-2.1956902468983084, loss:0.5042943253014793

(np.float64(5.051047623653049),
 np.float64(1.4569794548473887),
 np.float64(-2.9596534546250037))